export const LOGIN_CLIENT_START = 'LOGIN_CLIENT_START';
export const LOGIN_CLIENT_SUCCESS = 'LOGIN_CLIENT_SUCCESS';
export const LOGIN_CLIENT_FAILURE = 'LOGIN_CLIENT_FAILURE';

export const LOGIN_STAFF_START = 'LOGIN_STAFF_START';
export const LOGIN_STAFF_SUCCESS = 'LOGIN_STAFF_SUCCESS';
export const LOGIN_STAFF_FAILURE = 'LOGIN_STAFF_FAILURE';

export const SIGNUP_CLIENT_START = 'SIGNUP_CLIENT_START';
export const SIGNUP_CLIENT_SUCCESS = 'SIGNUP_CLIENT_SUCCESS';
export const SIGNUP_CLIENT_FAILURE = 'SIGNUP_CLIENT_FAILURE';

export const FETCH_ACCOUNT_DETAILS_START = 'FETCH_ACCOUNT_DETAILS_START';
export const FETCH_ACCOUNT_DETAILS_SUCCESS = 'FETCH_ACCOUNT_DETAILS_SUCCESS';
export const FETCH_ACCOUNT_DETAILS_FAILURE = 'FETCH_ACCOUNT_DETAILS_FAILURE';

export const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START';
export const CREATE_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_DETAILS_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'FETCH_ACCOUNT_DETAILS_FAILURE';

export const FETCH_ALL_ACCOUNTS_START = 'FETCH_ALL_ACCOUNTS_START';
export const FETCH_ALL_ACCOUNTS_SUCCESS = 'FETCH_ALL_ACCOUNTS_SUCCESS';
export const FETCH_ALL_ACCOUNTS_FAILURE = 'FETCH_ALL_ACCOUNTS_FAILURE';

export const FETCH_ALL_ACTIVE_ACCOUNTS_START = 'FETCH_ALL_ACTIVE_ACCOUNTS_START';
export const FETCH_ALL_ACTIVE_ACCOUNTS_SUCCESS = 'FETCH_ALL_ACTIVE_ACCOUNTS_SUCCESS';
export const FETCH_ALL_ACTIVE_ACCOUNTS_FAILURE = 'FETCH_ALL_ACTIVE_ACCOUNTS_FAILURE';

export const FETCH_ALL_DORMANT_ACCOUNTS_START = 'FETCH_ALL_DORMANT_ACCOUNTS_START';
export const FETCH_ALL_DORMANT_ACCOUNTS_SUCCESS = 'FETCH_ALL_DORMANT_ACCOUNTS_SUCCESS';
export const FETCH_ALL_DORMANT_ACCOUNTS_FAILURE = 'FETCH_ALL_DORMANT_ACCOUNTS_FAILURE';

